function D = fs_distance_matrix(A,B)

% A : matrix  N x 3
% B : matrix  M x 3
% D : matrix  N x M
% edited by long  2013-4-16
%%
ones_surf = ones(1,length(B(:,1)));
ones_ras = ones(1,length(A(:,1)));
% distance between A and B
D = sqrt((ones_surf' * A(:,1)'.^2)' - ...
    2* A(:,1) * B(:,1)' + ... ...
    (ones_ras' * B(:,1)'.^2) + ...
    (ones_surf' * A(:,2)'.^2)' - ...                       
    2* A(:,2) * B(:,2)' + ...
    (ones_ras' * B(:,2)'.^2) + ...
    (ones_surf' * A(:,3)'.^2)' - ...
    2* A(:,3) * B(:,3)' + ...
    (ones_ras' * B(:,3)'.^2));
end